### ISSUE TITLE
xp and advp

### ISSUE THREAD

**Issue by savary** [kawu/walenty#2]
The macros for phrase types include
**xp(locat)** which rewrites to **advp(locat)**, which in its turn rewrites to _blisko_, _daleko_, etc.
In other words each xp phrase can rewrite to a simple adverb. What is then the type of this phrase?

**Comment by kawu** [comment]
My current guess is that this simple adverb specifies the lexical head of the phrase.  Thus the type will be **advp(locat)**, ~~embedded in **xp(locat)**,~~ with the base form constrained to one of _blisko_, _daleko_, etc.

**Comment by kawu** [comment]
For instance, the following extract from the expansion file:

```
advp(adl) ->
    blisko
    ...
```

can be treated as:

```
advp(adl) ->
    lex(advp,_,'blisko',atr)
    ...
```
